name: app-handler-s3-eventsource-plugin
description: Plugin que adiciona uma fonte de eventos a stack de handlers.
types:
  - app
inputs:
  - label: Nome de referência do Bucket S3.
    type: text
    name: bucket_name
    default: bucket_name
    required: true
  - label: ARN (Amazon Resource Naming) de um bucket já existente? (se informado a o plugin usa o bucket já existente como fonte de eventos)
    type: text
    name: bucket_arn
    default: ''
    required: false
  - label: Você pretente fazer uma extração e/ou transformação dos objetos recebidos pelo bucket (Throtled) ou simplesmente receber os eventos de criação de objetos do bucket (Simple)? (Esta opção cria uma fila SQS e uma lambda de tratamento padrão para os objetos recebidos, garantindo também resiliencia ao lidar com o tratamento desses dados)
    type: text
    name: extract_event_source_type
    items:
      - 'Simple'
      - 'Throtled'
    default: 'Simple'
    required: false
  - label: Nome da lambda de extração/transformação
    type: text
    name: extract_lambda_name
    default: 'extract-lambda'
    condition:
      variable: extract_event_source_type
      operator: ==
      value: 'Throtled'

hooks:
  - type: edit
    trigger: after-render
    path: infra/lib/{{handler_name}}-handler-stack.ts
    changes:
      - search:
          string: "const handlerCore = new stkHandler.StackSpotLambdaHandlerCore(this,"
          insert-after:
            snippet: snippets/typescript-add-lambda-eventsource.txt
  - type: run
    trigger: after-render
    commands:
      - npm run infra:install:handlercore
      - npm run infra:format:fix
      - npm run infra:build:cdk
      - npm run source:setup

displayName: S3 EventSource Plugin

category: Backend

compatibility:
  - NodeJS 14.x

about: about.md

usage: usage.md

useCase: useCase.md

implementation: implementation.md

technologies: [ "Typescript", "AWS S3" ]